name: Initialize Wiki
on: workflow_dispatch
jobs:
  init-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push wiki pages
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          WIKI_DIR: .wiki-pages/
          GH_TOKEN: ${{ secrets.WIKI_PAT }}
          GH_MAIL: agentsreenivasa@gmail.com
          GH_NAME: agentsreenivasa
